server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: yang
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.200.130
    port: 6379
    password: yang

#  servlet:
#    multipart:
#      max-file-size: 2MB
#      max-request-size: 5MB
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
oss:
  accessKey: 1j5PLQNSHfous9AYWi4v_HEXQh7UPcDZr23FLZd1
  secretKey: iFybJTTYnB01RWT71yBbLxZj-Odc2Dqap1_O0lut
  bucket: ywb-blog